spring:
  application:
    name: safeGuard
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/capstone
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3600000
  mail:
    host: smtp.gmail.com
    port: 587
    username: dragon117@kyonggi.ac.kr
    password: ${EMAIL_AUTH}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa